import nodemailer from "nodemailer";
import * as handlebars from "handlebars";
import { portfolioTemplate } from "./templates/portfolio";

// function responsible to send the email
export async function sendMail({
  to, //email tha will receive the message
  name, //recipient of the emal
  subject, //subject of the email
  body, //body of the emal
  from,
}: {
  to: string;
  name: string;
  subject: string;
  body: string;
  from:string
}) {
    // get theses variable from the .env file
  const { SMTP_EMAIL, SMTP_PASSWORD } = process.env;

//   here we fdefine a nodemailer transport
  const transport = nodemailer.createTransport({
    service: "gmail", //the mail server is "gmail"
    // google account authetication of the user that want to send this email
    auth: {
      user: SMTP_EMAIL, //the user email
      pass: SMTP_PASSWORD, //the passwordgenerated by this account
    },
  });

//   let test our transport
  try {
    // we verify he transport
    const testResult = await transport.verify();
    console.log(testResult);
  } catch (error) {
    console.error({ error });
    return;
  }

//   if the transport pass, here we send the email
  try {
    const sendResult = await transport.sendMail({
      from: from,//SMTP_EMAIL, //this email is from "SMTP_EMAIL"(juniorsemerzir@gmail.com).email address of the sender
      to,//email receiver.<==>to:to (that means we send the email to the same email, we do this because we don't have another email test test)
      subject, 
      html: body,
    });
    console.log(sendResult);
  } catch (error) {
    console.log(error);
  }
}


// here we create a component/function called "compileEfesTemplate"
//that will take these parameters and add it to the html template
export function compilePortfolioTemplate(
    content:string,
    email:string,
    phone:string,
    service:string,
    firstname:string, 
    lastname:string
    ) {
    // here we call "handlebars" to compile the html template called "efesTemplate"
    const template = handlebars.compile(portfolioTemplate);
    const htmlBody = template({
        content,
        email,
        phone,
        service,
        firstname,
        lastname
    });
    return htmlBody;
  }